#!/usr/bin/env python3
"""
Generate the study-specific JS data files.

Sources (R2/R5 layout):
    study/study.yaml              — study meta + segment registry
                                    (identity, party, canonical pop shares)
    study/judgments.xlsx          — analyst judgments only
                                    (Messages + SegmentMetrics sheets)
    prism_variants.json           — message count (derived from the
                                    variants workbook by the parser)

Outputs:
    src/data/study.js             — STUDY_META, MESSAGES, STUDY_METRICS,
                                    ASSIGNED_TIERS, PREPOST_METRICS, K
    src/data/studyData.js         — DATA.segments skeleton (from registry)
                                    + DATA.HIV block (from judgments)
    src/data/generated/segments.js — THE segment table for React pages
                                    (id, code, name, party, pop, popShare)

K (number of pre-post items) is auto-detected from the workbook.

Usage:  python pipeline/extract_study.py   (from the repo root)
"""
import json
import re
import sys
from pathlib import Path

_PIPELINE = Path(__file__).resolve().parent
sys.path.insert(0, str(_PIPELINE))
from study_config import load_config, n_messages
import workbook as wbmod

WORKBOOK = None  # resolved from config below

_cfg = load_config()
WORKBOOK = _cfg["sources"]["judgments_workbook"]
REGISTRY = _cfg["segment_registry"]
SEG_ORDER = [r["code"] for r in REGISTRY]


def js_str(s):
    return json.dumps(s, ensure_ascii=False)


def write_study_js(messages, sm, prepost_labels, K):
    s = _cfg["study"]
    L = []
    L.append("// ═══════════════════════════════════════════════════════════════")
    L.append(f"// STUDY-SPECIFIC — {s['topic']}")
    L.append(f"// Client: {s['client']}")
    L.append(f"// Field date: {s['field_dates']}")
    L.append("// Generated by pipeline/extract_study.py — do not edit by hand.")
    L.append("// ═══════════════════════════════════════════════════════════════")
    L.append("")
    L.append("export const STUDY_META = {")
    L.append(f"  name: {js_str(s['short_name'])},")
    L.append(f"  client: {js_str(s['client'])},")
    L.append(f"  topic: {js_str(s['topic'])},")
    L.append(f"  fieldDate: {js_str(s['field_dates'])},")
    L.append(f"  nMessages: {n_messages(_cfg)},")
    L.append(f"  methodology: {js_str(s['methodology'])},")
    L.append("};")
    L.append("")
    L.append(f"// K = number of pre-post items extracted from the workbook (auto-detected).")
    L.append(f"export const K_PREPOST = {K};")
    L.append("")
    L.append("// ─── MESSAGES (Wave 1: core text only, no per-segment variants or SoP yet) ───")
    L.append("export const MESSAGES = [")
    for m in messages:
        L.append(f"  {{ id:{m['id']}, shortName:{js_str(m['shortName'])}, theme:{js_str(m['theme'])}, text:{js_str(m['text'])} }},")
    L.append("];")
    L.append("")
    L.append("// SoP matrices intentionally empty for Wave 1. MessageMap renders a wave-2 placeholder.")
    L.append("export const CONTROL_SOP = [];")
    L.append("export const VARIANT_SOP = [];")
    L.append("")
    L.append("// ─── ASSIGNED TIERS (explicit, from workbook 'tier' column) ───")
    L.append("// Tiers are analyst-configured in the workbook, never derived from ROI.")
    L.append("export const ASSIGNED_TIERS = {")
    for code in SEG_ORDER:
        if code in sm and sm[code].get("tier") is not None:
            L.append(f"  {code}: {sm[code]['tier']},")
    L.append("};")
    L.append("")
    L.append("export function getAssignedTier(code) { return ASSIGNED_TIERS[code] || 3; }")
    L.append("")
    L.append("// ─── SEGMENT-LEVEL STUDY METRICS ───")
    L.append("export const STUDY_METRICS = {")
    for code in SEG_ORDER:
        if code not in sm:
            continue
        m = sm[code]
        prepost_str = ",".join(f"{k}:{json.dumps(v)}" for k, v in m["prePost"].items())
        tier = m["tier"] if m["tier"] is not None else "null"
        persuadable_val = m.get('persuadable', 0)
        L.append(f"  {code}: {{ tier:{tier}, roi:{m['roi']}, highRoi:{m['highRoi']}, persuadable:{persuadable_val}, supporters:{m['supporters']}, activation:{m['activation']}, influence:{m['influence']}, persuadability:{json.dumps(m['persuadability'])}, prePost:{{{prepost_str}}} }},")
    L.append("};")
    L.append("")
    L.append(f"// ─── PRE/POST METRIC DEFINITIONS (K={K} items) ───")
    L.append("export const PREPOST_METRICS = [")
    for pp in prepost_labels:
        L.append(f"  {{ key:{js_str(pp['key'])}, label:{js_str(pp['label'])}, question:{js_str(pp['question'])}, scale:{js_str(pp['scale'])} }},")
    L.append("];")
    L.append("")
    L.append("// ─── THEME COLORS (intentionally empty for HIV Wave 1) ───")
    L.append("export const THEME_COLORS = {};")
    L.append("")
    L.append("export const TIER_CONFIG = {")
    L.append('  1: { bg:"#064e3b", text:"#6ee7b7", accent:"#34d399", label:"TIER 1" },')
    L.append('  2: { bg:"#854d0e", text:"#fde047", accent:"#eab308", label:"TIER 2" },')
    L.append('  3: { bg:"#991b1b", text:"#fca5a5", accent:"#ef4444", label:"TIER 3" },')
    L.append("};")
    L.append("")
    L.append("// Deprecated: tier is always analyst-configured via ASSIGNED_TIERS / getAssignedTier(code).")
    L.append("// Kept here so existing imports don't break; do not call from new code.")
    L.append("export function getTierNum(roi) { return roi >= 1.07 ? 1 : roi >= 1.00 ? 2 : 3; }")
    L.append("")
    L.append("export function getSopColor(v) {")
    L.append('  if (v >= 13) return { bg:"#065f46", t:"#6ee7b7" };')
    L.append('  if (v >= 11) return { bg:"#064e3b", t:"#6ee7b7" };')
    L.append('  if (v >= 10) return { bg:"#1a3a2a", t:"#a7f3d0" };')
    L.append('  if (v >= 9)  return { bg:"#1e293b", t:"#cbd5e1" };')
    L.append('  if (v >= 8)  return { bg:"#1a1f2e", t:"#94a3b8" };')
    L.append('  if (v >= 7)  return { bg:"#1a1520", t:"#94a3b8" };')
    L.append('  if (v >= 6)  return { bg:"#1f1318", t:"#f9a8a8" };')
    L.append('  return { bg:"#2d1215", t:"#fca5a5" };')
    L.append("}")
    L.append("")
    L.append('export const PERSUADABILITY_LABELS = ["Highest ROI","Strong ROI","Persuadable","No persuasion","Backfire"];')
    L.append("")

    out = "\n".join(L)
    with open("src/data/study.js", "w", encoding="utf-8") as f:
        f.write(out)
    print(f"Wrote src/data/study.js ({len(out)} bytes, K={K})")


def write_study_data_js(messages, sm, prepost_labels):
    """Regenerate studyData.js wholesale: the DATA.segments skeleton comes
    from the registry (single source — no more hand-maintained copy), the
    HIV block carries the workbook judgments."""
    skeleton = [{
        "id": r["id"], "code": r["code"], "name": r["name"],
        "party": r["party"], "pop": round(r["pop_share"] * 100),
    } for r in REGISTRY]

    hiv_segments = []
    for i, r in enumerate(REGISTRY, start=1):
        code = r["code"]
        if code not in sm:
            continue
        m = sm[code]
        hiv_segments.append({
            "id": i, "code": code, "name": r["name"], "party": r["party"],
            "pop": round(r["pop_share"] * 100),
            "roi": m["roi"], "highRoi": m["highRoi"], "tier": m["tier"],
            "persuadability": m["persuadability"],
            "supporters": m["supporters"], "activation": m["activation"], "influence": m["influence"],
            "prePost": m["prePost"],
        })

    hiv_messages = [
        {"id": m["id"], "shortName": m["shortName"], "text": m["text"], "theme": m["theme"], "sop": []}
        for m in messages
    ]

    data = {
        "segments": skeleton,
        "HIV": {
            "segments": hiv_segments,
            "messages": hiv_messages,
            "prePostMetrics": prepost_labels,
        },
    }
    body = json.dumps(data, indent=2, ensure_ascii=False)
    content = (
        "// ═══════════════════════════════════════════════════════════════\n"
        "// GENERATED by pipeline/extract_study.py — do not edit by hand.\n"
        "// DATA.segments comes from the study/study.yaml segment registry\n"
        "// (canonical names, party, population shares); the HIV block\n"
        "// carries the analyst judgments from study/judgments.xlsx.\n"
        "// ═══════════════════════════════════════════════════════════════\n"
        "\n"
        f"const DATA = {body};\n"
        "\n"
        "export default DATA;\n"
    )
    with open("src/data/studyData.js", "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote src/data/studyData.js ({len(content)} bytes)")


def write_generated_segments_js():
    """src/data/generated/segments.js — THE segment table for React pages."""
    Path("src/data/generated").mkdir(parents=True, exist_ok=True)
    L = []
    L.append("// ═══════════════════════════════════════════════════════════════")
    L.append("// GENERATED by pipeline/extract_study.py — do not edit by hand.")
    L.append("// Source: study/study.yaml segment_registry. This is THE segment")
    L.append("// table (identity, party, canonical population shares) for the")
    L.append("// React layer. pop = integer percent; popShare = exact fraction.")
    L.append("// ═══════════════════════════════════════════════════════════════")
    L.append("")
    L.append("export const SEGMENTS = [")
    for r in REGISTRY:
        L.append(f"  {{ id: {r['id']}, code: {js_str(r['code'])}, name: {js_str(r['name'])}, "
                 f"party: {js_str(r['party'])}, pop: {round(r['pop_share'] * 100)}, popShare: {r['pop_share']} }},")
    L.append("];")
    L.append("")
    L.append("export const SEG_BY_CODE = Object.fromEntries(SEGMENTS.map(s => [s.code, s]));")
    L.append("")
    L.append("export default SEGMENTS;")
    L.append("")
    out = "\n".join(L)
    with open("src/data/generated/segments.js", "w", encoding="utf-8") as f:
        f.write(out)
    print(f"Wrote src/data/generated/segments.js ({len(out)} bytes)")


def _overlay_dashboard_roi(sm):
    """Overlay fresh per-segment ROI values from src/data/topline/
    dashboard.json (computed by compute_core.py from the .sav, with
    workbook + study.yaml overrides already applied) on top of the
    workbook-cached SegmentMetrics.

    This is what makes the /audience-roi page reflect each .sav refresh:
    workbook provides the structural fields (persuadability buckets,
    prePost item series), dashboard.json.roi_data provides the live
    numeric fields. dashboard.json wins.

    Mapping (dashboard.json.roi_data → JS-side study.js):
      composite_roi      → roi          (Decipher-rooted composite)
      pct_highest        → highRoi      (% of seg in XROI_cat=Highest)
      coalition_support  → supporters   (workbook judgment, passed through)
      activation_prob    → activation   (workbook overrides computed)
      influence_pct      → influence    (workbook judgment, passed through)
      priority_tier      → tier         (YAML > workbook)
    """
    import json as _json
    dash_path = Path(__file__).resolve().parent.parent / 'src' / 'data' / 'topline' / 'dashboard.json'
    if not dash_path.exists():
        print(f"  (no dashboard.json yet at {dash_path}; using workbook values)")
        return sm
    try:
        with open(dash_path, encoding='utf-8') as f:
            dash = _json.load(f)
    except Exception as e:
        print(f"  WARNING: couldn't load dashboard.json: {e}; using workbook values")
        return sm
    roi_data = dash.get('roi_data') or {}
    if not roi_data:
        print(f"  (dashboard.json.roi_data is empty; using workbook values)")
        return sm

    # prePost from pp_results — STUDY_METRICS.prePost is EXACTLY the
    # topline pre/post composite percentages, per analyst direction.
    # PP{N} → item{N}; each value is [pre_top3, post_top3] per segment.
    pp_results = dash.get('pp_results') or {}
    n_pp = 0
    for pp_key, pp_block in pp_results.items():
        m = re.match(r'PP(\d+)$', pp_key)
        if not m:
            continue
        item_key = f"item{m.group(1)}"
        pre_seg = (pp_block.get('pre') or {})
        post_seg = (pp_block.get('post') or {})
        for code in sm.keys():
            pre_v = (pre_seg.get(code) or {}).get('top3')
            post_v = (post_seg.get(code) or {}).get('top3')
            if pre_v is None and post_v is None:
                continue
            sm[code].setdefault('prePost', {})
            sm[code]['prePost'][item_key] = [
                round(float(pre_v), 1) if pre_v is not None else None,
                round(float(post_v), 1) if post_v is not None else None,
            ]
            n_pp += 1
    if n_pp:
        print(f"Overlaid {n_pp} prePost values from dashboard.json.pp_results")

    mapping = (
        ('composite_roi',     'roi',          lambda v: round(float(v), 4)),
        ('pct_high_roi',      'highRoi',      lambda v: round(float(v))),
        ('pct_movable',       'persuadable',  lambda v: round(float(v))),
        ('coalition_support', 'supporters',   lambda v: round(float(v))),
        ('activation_prob',   'activation',   lambda v: round(float(v))),
        ('influence_pct',     'influence',    lambda v: round(float(v))),
        ('priority_tier',     'tier',         lambda v: int(v)),
        # Persuadability bar chart on /audience-roi reads this 5-bucket
        # array; display order corresponds to XROI_cat 5..1:
        #   [Highest ROI, Strong ROI, Persuadable, No persuasion, Backfire]
        ('persuadability',    'persuadability', lambda v: [int(round(x)) for x in v]),
    )
    n_overlaid = 0
    for code, cell in roi_data.items():
        if code not in sm:
            continue
        for dash_key, js_key, conv in mapping:
            v = cell.get(dash_key)
            if v is None:
                continue
            try:
                sm[code][js_key] = conv(v)
                n_overlaid += 1
            except Exception:
                pass
    print(f"Overlaid {n_overlaid} fields from dashboard.json.roi_data "
          f"onto {len(roi_data)} segments")
    return sm


def main():
    wb = wbmod.load(WORKBOOK)
    messages = wbmod.read_messages(wb)
    sm, prepost_labels, K = wbmod.read_segment_metrics(wb)
    print(f"Detected K={K} pre-post items.")

    sm = _overlay_dashboard_roi(sm)

    write_study_js(messages, sm, prepost_labels, K)
    write_study_data_js(messages, sm, prepost_labels)
    write_generated_segments_js()
    print(f"Done. K={K}, {len(messages)} messages, {len(sm)} segments.")


if __name__ == "__main__":
    main()
